## Step 1 : Load the data

In [26]:
import wrds
import pandas as pd
from datetime import datetime

# Connect to WRDS
db = wrds.Connection(wrds_username='pherb127')

Loading library list...
Done

In [42]:
# Import Country Data
data=db.raw_sql("SELECT * FROM wrdsapps_windices.mwcountryreturns "
               "WHERE Country IN ('AUSTRALIA','FRANCE','GERMANY','JAPAN','SWITZERLAND','UNITED KINGDOM') "
               "AND Date BETWEEN '2002-01-01' AND '2024-12-31'")
data.to_csv('country_data.csv', sep=';', index=False)
data = pd.read_csv("country_data.csv", sep=';')

In [43]:
data.head()

   fic        date    country currency  mportret  mportretx
0  AUS  2002-01-31  AUSTRALIA      AUD  0.027358   0.027313
1  AUS  2002-02-28  AUSTRALIA      AUD -0.001832  -0.004358
2  AUS  2002-03-28  AUSTRALIA      AUD  0.005199  -0.001914
3  AUS  2002-04-30  AUSTRALIA      AUD -0.014302  -0.015424
4  AUS  2002-05-31  AUSTRALIA      AUD -0.000204  -0.001752

In [47]:
# Import US Data
# 2. Download the monthly value-weighted total return
crsp_vw = db.raw_sql(
    """
    SELECT
      date,
      vwretd      -- value-weighted total return (with dividends)
    FROM crsp.msi
    WHERE date BETWEEN '2002-01-01' AND '2024-12-31'
    """,
    date_cols=['date']
)

# 3. Save to CSV
crsp_vw.to_csv('crsp_value_weighted_returns.csv', sep=";", index=False)
crsp = pd.read_csv("crsp_value_weighted_returns.csv", sep=';')

In [48]:
crsp.head()

         date    vwretd
0  2002-01-31 -0.015966
1  2002-02-28 -0.021700
2  2002-03-28  0.044698
3  2002-04-30 -0.049600
4  2002-05-31 -0.010510